# Generated by Django 4.0.4 on 2022-05-07 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100)),
                ('summary', models.TextField(verbose_name='Краткое содержание')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('date', models.CharField(max_length=150, null=True, verbose_name='Месяц и год')),
            ],
            options={
                'verbose_name': 'Выполненные заказы',
                'verbose_name_plural': 'Выполненные заказы',
            },
        ),
        migrations.CreateModel(
            name='WorkShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='completed_work/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='completed_work.work')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
