# Generated by Django 4.0.4 on 2022-05-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completed_work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='date',
        ),
    ]
