# Generated by Django 4.0.4 on 2022-04-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100)),
                ('summary', models.CharField(help_text="Нужно заполнять если выбрат пункт 'На главной странице'.", max_length=150, verbose_name='Краткое содержание')),
                ('display_on_main', models.BooleanField(default=False, verbose_name='На главной странице')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
