# Generated by Django 4.0.4 on 2022-04-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='summary',
            field=models.TextField(help_text="Нужно заполнять если выбрат пункт 'На главной странице'.", max_length=150, verbose_name='Краткое содержание'),
        ),
    ]
