# Generated by Django 4.0.4 on 2022-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='summary',
            field=models.TextField(help_text="Нужно заполнять если выбран пункт 'На главной странице'.", verbose_name='Краткое содержание'),
        ),
    ]
